# Phase 35: portable PDF audit artifact for a single run. Renders only
# already-persisted, already-computed data (digest paragraph from Phase 30.3,
# Signal/Change/Evidence/Failure/RecoveryAttempt rows) - this module performs
# no calculations of its own (engineering guidelines, section 5: percentages/comparisons are
# deterministic and computed once, upstream, never re-derived here or by an
# LLM). reportlab is pure Python (no system .so deps), matching the repo's
# "simple, reproducible Docker build" priority over WeasyPrint/Pango/Cairo.
from __future__ import annotations

import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)
from sqlalchemy.orm import Session

from agents.digest import generate_run_digest
from backend.app.database.object_storage import get_object_bytes
from backend.app.models.evidence import Evidence
from backend.app.models.failure import Failure, RecoveryAttempt
from backend.app.models.model_invocation import ModelInvocation
from backend.app.models.plan import Plan
from backend.app.models.run import Run
from backend.app.models.signal import Signal
from backend.app.models.snapshot import Change, Snapshot
from backend.app.models.task import Task
from backend.app.models.user import Role, User


class RunNotFoundError(Exception):
    pass


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="SectionHeading", parent=styles["Heading2"], spaceBefore=14, spaceAfter=6))
    styles.add(ParagraphStyle(name="SmallMuted", parent=styles["Normal"], fontSize=8, textColor=colors.grey))
    styles.add(ParagraphStyle(name="LabelBold", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=9))
    styles.add(ParagraphStyle(name="CellText", parent=styles["Normal"], fontSize=8, leading=10))
    return styles


def _table(rows: list[list[str]], col_widths: list[float] | None = None) -> Table:
    style_sheet = _styles()
    wrapped = [
        [Paragraph(str(cell) if cell is not None else "-", style_sheet["CellText"]) for cell in row]
        for row in rows
    ]
    t = Table(wrapped, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2b3a55")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#c7ccd6")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f6fa")]),
    ]))
    return t


def build_run_report(db: Session, run_id: str, *, generated_by_user: User | None = None) -> bytes:
    run = db.get(Run, run_id)
    if run is None:
        raise RunNotFoundError(f"Run '{run_id}' not found.")

    task = db.get(Task, run.task_id)
    plan = db.get(Plan, run.plan_id) if run.plan_id else None

    styles = _styles()
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=1.5 * cm, bottomMargin=1.5 * cm, leftMargin=1.5 * cm, rightMargin=1.5 * cm,
        title=f"Run Report {run.id}",
    )
    story: list = []

    # --- 1. Header --------------------------------------------------------
    story.append(Paragraph("MakeMyTrip Web Operations Agent, Run Report", styles["Title"]))
    story.append(Spacer(1, 4))
    generated_at = datetime.now(timezone.utc).isoformat()
    if generated_by_user is not None:
        role = db.get(Role, generated_by_user.role_id)
        generated_by = f"{generated_by_user.display_name} ({role.name if role else 'unknown role'})"
    else:
        generated_by = "system"

    header_rows = [
        ["Field", "Value"],
        ["Task objective", task.objective if task else "-"],
        ["Workflow type", task.workflow_type if task else "-"],
        ["Entity", task.entity_key if task else "-"],
        ["Task ID", task.id if task else "-"],
        ["Run ID", run.id],
        ["Plan ID", plan.id if plan else "-"],
        ["Run state", run.state],
        ["Generated at (UTC)", generated_at],
        ["Generated by", generated_by],
    ]
    story.append(_table(header_rows, col_widths=[5 * cm, 11.5 * cm]))

    # --- 2. Executive Summary (AI-generated) -------------------------------
    story.append(Paragraph("Executive Summary", styles["SectionHeading"]))
    digest = generate_run_digest(db, run_id)
    is_ai_generated = digest.generated_by != "deterministic"
    label = (
        "AI-generated summary. Gemini 2.5 Flash."
        if is_ai_generated
        else "Deterministic fallback summary (no AI model call was used for this run's digest)."
    )
    story.append(Paragraph(label, styles["LabelBold"]))

    if is_ai_generated:
        invocation = (
            db.query(ModelInvocation)
            .filter(ModelInvocation.run_id == run_id, ModelInvocation.node == "digest", ModelInvocation.success.is_(True))
            .order_by(ModelInvocation.created_at.desc())
            .first()
        )
        if invocation:
            story.append(Paragraph(f"Model invocation ID: {invocation.id}", styles["SmallMuted"]))

    story.append(Spacer(1, 4))
    story.append(Paragraph(digest.executive_summary, styles["Normal"]))
    if digest.bullets:
        for b in digest.bullets:
            story.append(Paragraph(f"- {b}", styles["Normal"]))

    # --- 3. Key Signals table ----------------------------------------------
    story.append(Paragraph("Key Signals", styles["SectionHeading"]))
    signals = db.query(Signal).filter(Signal.run_id == run_id).order_by(Signal.created_at).all()
    if signals:
        rows = [["Severity", "Observation", "Business impact", "Recommendation", "Confidence", "Owner"]]
        for s in signals:
            rows.append([
                s.severity, s.observations, s.business_impact or "-",
                s.recommendation or "-", f"{s.confidence:.2f}", s.owner or "-",
            ])
        story.append(_table(rows, col_widths=[1.8 * cm, 4 * cm, 3.7 * cm, 3.7 * cm, 1.8 * cm, 1.5 * cm]))
    else:
        story.append(Paragraph("No signals were generated for this run.", styles["Normal"]))

    # --- 4. Historical Comparison table (no re-computation) -----------------
    story.append(Paragraph("Historical Comparison", styles["SectionHeading"]))
    changes = db.query(Change).filter(Change.run_id == run_id).order_by(Change.created_at).all()
    if changes:
        rows = [["Field", "Previous", "Current", "Abs diff", "% diff", "Significance", "Noise filtered"]]
        for c in changes:
            rows.append([
                c.entity_name, c.previous_value or "-", c.current_value or "-",
                f"{c.abs_diff:g}" if c.abs_diff is not None else "-",
                f"{c.delta_pct:g}%" if c.delta_pct is not None else "-",
                c.significance, "yes" if c.is_noise else "no",
            ])
        story.append(_table(rows, col_widths=[3.2 * cm, 2.3 * cm, 2.3 * cm, 1.8 * cm, 1.8 * cm, 2.3 * cm, 2.3 * cm]))
    else:
        story.append(Paragraph("No historical comparison data is available for this run.", styles["Normal"]))

    # --- 5. Evidence Appendix ------------------------------------------------
    story.append(Paragraph("Evidence Appendix", styles["SectionHeading"]))
    evidence_rows = db.query(Evidence).filter(Evidence.run_id == run_id).order_by(Evidence.created_at).all()
    if evidence_rows:
        for e in evidence_rows:
            story.append(Paragraph("CURRENT OBSERVATION (live Playwright capture)", styles["LabelBold"]))
            if e.artifact_purged:
                story.append(Paragraph(
                    "Screenshot no longer available. Retention policy purged the stored artifact; "
                    "this metadata row is preserved.",
                    styles["Normal"],
                ))
            elif e.screenshot_object_key:
                try:
                    data, content_type = get_object_bytes(e.screenshot_object_key)
                    img_buf = io.BytesIO(data)
                    img = Image(img_buf, width=10 * cm, height=6 * cm, kind="proportional")
                    story.append(img)
                except Exception:
                    story.append(Paragraph("Screenshot could not be retrieved from evidence storage.", styles["Normal"]))
            else:
                story.append(Paragraph("No screenshot was captured for this evidence record.", styles["Normal"]))

            meta_rows = [
                ["Field", "Value"],
                ["Source URL", e.source_url],
                ["Selector used", e.selector or "-"],
                ["Extraction confidence", f"{e.confidence:.2f}" if e.confidence is not None else "-"],
                ["Captured at", e.captured_at],
            ]
            story.append(_table(meta_rows, col_widths=[4 * cm, 12.5 * cm]))
            story.append(Spacer(1, 8))
    else:
        story.append(Paragraph("No evidence records exist for this run.", styles["Normal"]))

    # --- 6. Recovery / Source Health notes -----------------------------------
    story.append(Paragraph("Recovery and Source Health Notes", styles["SectionHeading"]))
    failures = db.query(Failure).filter(Failure.run_id == run_id).order_by(Failure.created_at).all()
    if failures:
        rows = [["Error type", "Message", "Retryable", "Retry count", "Recovery state"]]
        for f in failures:
            rows.append([f.error_type, f.message, "yes" if f.retryable else "no", str(f.retry_count), f.recovery_state])
        story.append(_table(rows, col_widths=[3 * cm, 6.5 * cm, 2 * cm, 2 * cm, 3 * cm]))

        failure_ids = [f.id for f in failures]
        recoveries = (
            db.query(RecoveryAttempt)
            .filter(RecoveryAttempt.run_id == run_id, RecoveryAttempt.failure_id.in_(failure_ids))
            .order_by(RecoveryAttempt.created_at)
            .all()
        )
        if recoveries:
            story.append(Spacer(1, 6))
            rec_rows = [["Original strategy", "Recovery strategy", "Candidate selector", "Result", "Confidence"]]
            for r in recoveries:
                rec_rows.append([
                    r.original_strategy or "-", r.recovery_strategy or "-", r.candidate_selector or "-",
                    r.result, f"{r.confidence:.2f}" if r.confidence is not None else "-",
                ])
            story.append(_table(rec_rows, col_widths=[3.3 * cm, 3.3 * cm, 3.3 * cm, 2.3 * cm, 2.3 * cm]))
    else:
        story.append(Paragraph("No failures or recovery attempts were recorded for this run.", styles["Normal"]))

    # --- 7. Traceability footer -----------------------------------------------
    story.append(Paragraph("Traceability", styles["SectionHeading"]))
    snapshot_ids = [s.id for s in db.query(Snapshot).filter(Snapshot.run_id == run_id).all()]
    evidence_ids = [e.id for e in evidence_rows]
    change_ids = [c.id for c in changes]
    signal_ids = [s.id for s in signals]
    chain = (
        f"Task {task.id if task else '-'} -> Run {run.id} -> Plan {plan.id if plan else '-'} -> "
        f"Snapshot {', '.join(snapshot_ids) if snapshot_ids else '-'} -> "
        f"Evidence {', '.join(evidence_ids) if evidence_ids else '-'} -> "
        f"Change {', '.join(change_ids) if change_ids else '-'} -> "
        f"Signal {', '.join(signal_ids) if signal_ids else '-'}"
    )
    story.append(Paragraph(chain, styles["CellText"]))

    # --- 8. Footer stamp -------------------------------------------------------
    story.append(Spacer(1, 12))
    story.append(Paragraph(
        "Generated by MakeMyTrip Web Operations Agent. "
        "Extraction: deterministic Playwright/BeautifulSoup. "
        "Reasoning: Gemini 2.5 Flash. "
        "Evidence: MinIO-backed, tamper-evident.",
        styles["SmallMuted"],
    ))

    doc.build(story)
    return buffer.getvalue()
